# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f99899b88bd775c3c6f9209fcbdfc309a38aa217ab9f60c60c6a4660322f43ac1cb5e2d1c3ef97af1369112d6cb002c1e811fafe9660bcedb6b04dd85f8e4e7

test:
  secret_key_base: 509f45e70299c4e29c5ce30c72cff639b2362ebaa6082b27dc992871671614cdaa3f9b30e843715d00ce07a006feedcfc9f05b66d75fc232c1f6c2b644e24d88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
