# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f292dc83991d6011e9634f6a2492fad74fc7a5d70d79af76cb488908da303f57965562a2be683af9bc2c139811d3fccfa63d15eb6f9adb74c9364de592d2a8c6

test:
  secret_key_base: 6d9b50b605f95df475f6f08288363f28b9ea1cfacd63e80e2fbd385b22f1a626a11655889154f207098eb3178b4177da0d15f28c0c81761217457dcb3614a3b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
