# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d01ff1dc55e1d3184efa9e1d93b68a4f196f6e227d198ae7fef40487b55f0761d6d9ad4a511b624885ec673c2c44cde56539945d928acdb02c42cc9e9e224b3

test:
  secret_key_base: b4954c190ac2d2c4a20c1d2939e9833eed710a1b9e8fa26a0ddfe947335824ef00c07ae5035ec9e0c6b2d0e8ff4572c055b0312b0ecf1204c64569eb297f4a9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
